### ISSUE TITLE
New replies function doesn't work properly

### ISSUE THREAD

**Issue by piotr25691** [DiscordStyles/Slate#23]
The new replies function that Discord has added doesn't work properly with the theme.
![obraz](https://user-images.githubusercontent.com/71488561/99638093-0e3eb500-2a46-11eb-987e-f39fa594a2e0.png)

**Comment by Gibbu** [comment]
Fixed

**Comment by piotr25691** [comment]
By the way, in compact mode it still doesn't look all that good 
![obraz](https://user-images.githubusercontent.com/71488561/99769640-e8c5b000-2b06-11eb-8e46-a386e4004188.png)
